### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by mrmcan** [radxa/rock-bsp#1]
hi, i got an error when doing make. 

root@m-vmubuntu86radxa:/opt/radxa/rock-bsp# make
mkdir -p /opt/radxa/rock-bsp/tools/toolchain
git clone -n --depth 1  /opt/radxa/rock-bsp/tools/toolchain
fatal: repository '/opt/radxa/rock-bsp/tools/toolchain' does not exist
make: *** [tools/toolchain/.git] Error 128

**Comment by hipboi** [comment]
@mrmcan did you run ./config.sh board? can you paste `cat .config`

**Comment by mrmcan** [comment]
@hipboi yes i did ./config.sh rock_pro 

output of cat .config:

#board name
BOARD=rock_pro
TYPECHIP=rk31

#can be emmc.img, nand.img or sdcard.img
IMAGE_TARGET=nand.img

#configuration for u-boot
UBOOT_REPO="https://github.com/radxa/u-boot-rockchip.git"
UBOOT_REV=u-boot-rk3188
UBOOT_DEFCONFIG=rk30xx
UBOOT_EXTRA=

#configuration for linux kernel
KERNEL_REPO="https://github.com/radxa/linux-rockchip.git"
KERNEL_REV=radxa-stable-3.0
KERNEL_DEFCONFIG=radxa_rock_pro_linux_hdmi_defconfig
KERNEL_EXTRA=

#initrd
INITRD_REPO="https://github.com/radxa/initrd.git"
INITRD_REV=master

#linux-boot.img second
BOOTIMG_SECOND=/dev/null

#rootfs URL
BOARD_ROOTFS=linaro-trusty-desktop.ext4
BOARD_ROOTFS_URL="http://dl.radxa.com/rock_pro/images/rootfs/linaro-trusty-desktop.ext4.xz"
#BOARD_ROOTFS="debian-wheezy-server.ext4"
#BOARD_ROOTFS_URL="http://dl.radxa.com/rock_pro/images/rootfs/debian-wheezy-server.ext4.xz"
#all tools
MKBOOTIMG_REPO="https://github.com/neo-technologies/rockchip-mkbootimg.git"
MKBOOTIMG_REV=master

RKFLASHTOOL_REPO="https://github.com/radxa/rkflashtool.git"
RKFLASHTOOL_REV=master

#toolchain
TOOLCHAIN_REPO_x86_32="https://github.com/radxa/android-platform-prebuilts-gcc-linux-x86-arm-arm-eabi-4.6.git"
TOOLCHAIN_REV_x86_32=jb-release

TOOLCHAIN_REPO_x86_64="https://github.com/radxa/android-platform-prebuilts-gcc-linux-x86-arm-arm-eabi-4.6.git"
TOOLCHAIN64_REV_x86_64=kitkat-release

**Comment by hipboi** [comment]
@mrmcan currently rock-bsp only support Linux as host(32bit and 64bit). `uname -m` x86_32 or x86_64

**Comment by mrmcan** [comment]
@Hipboi its x86 based 32bit ubuntu14.04. I think there is a bug in makefile

**Comment by hipboi** [comment]
@mrmcan what's the output of `uname -m`

**Comment by mrmcan** [comment]
@hipboi 

root@m-vmubuntu86radxa:/opt/rock-bsp# uname -m
i686

**Comment by hipboi** [comment]
@mrmcan can you run `git pull` and run `./config.sh rock_pro` then `make` again?

**Comment by mrmcan** [comment]
root@m-vmubuntu86radxa:/opt/rock-bsp# git pull
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/radxa/rock-bsp
   76c95de..eaa6243  master     -> origin/master
Updating 76c95de..eaa6243
Fast-forward
 README.md         | 1 +
 configs/defconfig | 3 +++
 2 files changed, 4 insertions(+)
root@m-vmubuntu86radxa:/opt/rock-bsp# ./config.sh rock_pro
rock_pro configured. Now run `make`
root@m-vmubuntu86radxa:/opt/rock-bsp# make
mkdir -p /opt/rock-bsp/tools/toolchain
git clone -n --depth 1 "https://github.com/radxa/android-platform-prebuilts-gcc-linux-x86-arm-arm-eabi-4.6.git" /opt/rock-bsp/tools/toolchain
Cloning into '/opt/rock-bsp/tools/toolchain'...
remote: Counting objects: 497, done.
remote: Compressing objects: 100% (379/379), done.
remote: Total 497 (delta 83), reused 455 (delta 74), pack-reused 0
Receiving objects: 100% (497/497), 71.58 MiB | 963.00 KiB/s, done.
Resolving deltas: 100% (83/83), done.
Checking connectivity... done.
cd /opt/rock-bsp/tools/toolchain && git checkout jb-release && cd - > /dev/null
error: pathspec 'jb-release' did not match any file(s) known to git.
make: *** [tools/toolchain/.git] Error 1

**Comment by hipboi** [comment]
@mrmcan please run `git pull` and `rm -rf tools/toolchain/` and `make` again.

**Comment by mrmcan** [comment]
its working without problem
